<?php
declare(strict_types=1);

namespace App;

use Chubbyphp\SwooleRequestHandler\PsrRequestFactory;
use Chubbyphp\SwooleRequestHandler\SwooleResponseEmitter;
use Psr\Http\Server\RequestHandlerInterface;
use Swoole\Http\Response as SwooleResponse;
use Swoole\Http\Server;
use Swoole\Server\Task;
use Swoole\Constant;
use Swoole\Util;
use WordPressPsr\BucketWordPressRoutes;
use WordPressPsr\RequestHandler;
use Nyholm\Psr7\Factory\Psr17Factory;
use Swoole\Http\Request as SwooleRequest;
use Swoole\ExitException;
use WordPressPsr\Headers;

// The below causes all kinds of problems
// It may be possible to use Coroutines with a dropin wp-db and object cache
// These would be a huge effort.
// \Swoole\Runtime::enableCoroutine();

// Disable WordPress's built-in cron spawning.
// WordPress normally spawns a loopback HTTP request to wp-cron.php during page load.
// In a persistent Swoole process that loopback request calls exit(), crashing the worker.
// Cron jobs can be triggered externally via a real cron entry: wp cron event run --due-now
if ( ! defined( 'DISABLE_WP_CRON' ) ) {
	define( 'DISABLE_WP_CRON', true );
}

require __DIR__ . '/vendor/autoload.php';

$wordpres_path = __DIR__ . '/wordpress';

// Install a mu-plugin that captures wp_redirect() calls before exit() is invoked.
// Standard WordPress calls header("Location: ...") then exit() in wp_redirect().
// OpenSwoole converts exit() to ExitException. By the time ExitException is thrown,
// the headers are already sent (or buffered). The mu-plugin hooks wp_redirect to store
// the redirect URL and status in a global so the task worker catch block can build a
// proper PSR redirect response without relying on headers_list() or the wp_header action.
$mu_plugins_dir = $wordpres_path . '/wp-content/mu-plugins';
$mu_plugin_path = $mu_plugins_dir . '/swoole-redirect-capture.php';
if ( is_dir( $wordpres_path ) && ! file_exists( $mu_plugin_path ) ) {
	if ( ! is_dir( $mu_plugins_dir ) ) {
		mkdir( $mu_plugins_dir, 0755, true );
	}
	file_put_contents(
		$mu_plugin_path,
		'<?php' . PHP_EOL .
		'// Auto-generated by server.php — captures wp_redirect() for OpenSwoole ExitException handling.' . PHP_EOL .
		'add_filter(' . PHP_EOL .
		'    \'wp_redirect\',' . PHP_EOL .
		'    function ( $location, $status ) {' . PHP_EOL .
		'        $GLOBALS[\'_swoole_redirect\'] = array( \'location\' => $location, \'status\' => $status );' . PHP_EOL .
		'        return $location;' . PHP_EOL .
		'    },' . PHP_EOL .
		'    PHP_INT_MAX,' . PHP_EOL .
		'    2' . PHP_EOL .
		');' . PHP_EOL
	);
}

$http = new Server( '0.0.0.0', 8889 );

$http->set(
	array(
		Constant::OPTION_DOCUMENT_ROOT            => $wordpres_path,
		Constant::OPTION_ENABLE_STATIC_HANDLER    => true,
		Constant::OPTION_ENABLE_COROUTINE         => true,
		Constant::OPTION_WORKER_NUM               => Util::getCPUNum(),
		Constant::OPTION_TASK_WORKER_NUM          => BucketWordPressRoutes::MIN_REQUIRED_WORKERS,
		Constant::OPTION_TASK_ENABLE_COROUTINE    => true,
		// Note: /wp-admin is intentionally excluded — it contains PHP files that must be
		// processed by the request handler. Including it here causes Swoole's static file
		// handler to intercept /wp-admin/ requests and return 200 (directory listing) instead
		// of routing them through WordPress, which prevents auth_redirect() from firing the
		// expected 302 redirect to wp-login.php.
		Constant::OPTION_STATIC_HANDLER_LOCATIONS => array( '/wp-content', '/wp-includes' ),
	)
);

$http->on(
	'start',
	function ( Server $server ): void {
		echo 'Swoole http server is started at http://0.0.0.0:8889' . PHP_EOL;
		echo 'WorkerID:' . $server->getWorkerId() . PHP_EOL;
		echo 'ManagerPid:' . $server->getManagerPid() . PHP_EOL;
		echo 'MasterPid:' . $server->getMasterPid() . PHP_EOL;
	}
);

$http->on(
	'WorkerStart',
	function ( $serv, $worker_id ) use ( $wordpres_path ) {
		global $argv;
		if ( $worker_id >= $serv->setting['worker_num'] ) {
			Util::setProcessName( "php {$argv[0]} task worker" );
		} else {
			Util::setProcessName( "php {$argv[0]} event worker" );
		}
		if ( function_exists( 'opcache_reset' ) ) {
			opcache_reset();
		}

		clearstatcache();
		error_log( "Worker #$worker_id started" );
	}
);

$task_workers = new BucketWordPressRoutes();

for ( $i = 0; $i < $http->setting['task_worker_num']; $i++ ) {
	$task_workers->addWorker( $i );
}

$psr17 = new Psr17Factory();
/**
 * @var RequestHandlerInterface $app
*/
$app = new RequestHandler( $wordpres_path, $psr17, $psr17 );

$swoole_response_emitter = new SwooleResponseEmitter();
$psr_request_factory     = new PsrRequestFactory(
	$psr17,
	$psr17,
	$psr17
);

$http->on(
	'request',
	function (
		SwooleRequest $swoole_request,
		SwooleResponse $swoole_response
	) use (
		$app,
		$task_workers,
		$http,
		$psr_request_factory,
		$swoole_response_emitter
	) {
		$request   = $psr_request_factory->create( $swoole_request );
		$worker_id = $task_workers->getWorkerForRequest( $request );
		if ( BucketWordPressRoutes::DO_NOT_USE_WORKER === $worker_id ) {
			try {
				$response = $app->handle( $request );
				$swoole_response_emitter->emit( $response, $swoole_response );
			} catch ( ExitException $e ) {
				// WordPress code usually does not call exit directly anymore but sometime it does.
				error_log( $e->getMessage() );
				if ( 'wp-load.php' === basename( $e->getFile() ) ) {
					// WordPress died loading probably missing wp-config.php redirecting to setup.
					$swoole_response->status( 302 );
					$swoole_response->header( 'Location', wp_guess_url() . '/wp-admin/setup-config.php' );
				} else {
					$swoole_response->status( 200 );
					$swoole_response->write( 'WordPress called exit when it shouldn\'t probably it\'s a <a href="https://github.com/WordPress-PSR/swoole/issues/new">bug</a>.' );
				}
				$swoole_response->end();
			}
		} else {
			$http->task(
				$request,
				$worker_id,
				function ( Server $server, $task_id, $data ) use ( $swoole_response, $swoole_response_emitter ) {
					$swoole_response_emitter->emit( $data, $swoole_response );
				}
			);
		}
	}
);

$http->on(
	'task',
	function ( Server $server, Task $task ) use ( $app, $task_workers, $psr17 ) {
		// Capture wp_redirect() calls before exit() is invoked.
		// WordPress calls wp_redirect($url, $status) then exit(). In OpenSwoole,
		// exit() becomes ExitException. We hook wp_redirect to store the redirect
		// info so the catch block can build a proper PSR response.
		$redirect_info = array(
			'location' => null,
			'status'   => 302,
		);
		$redirect_filter = function ( $location, $status ) use ( &$redirect_info ) {
			$redirect_info['location'] = $location;
			$redirect_info['status']   = $status;
			return $location;
		};

		// Register the filter if WordPress is loaded (it will be after first bootstrap).
		if ( function_exists( 'add_filter' ) ) {
			add_filter( 'wp_redirect', $redirect_filter, PHP_INT_MAX, 2 );
		}

		try {
			$response = $app->handle( $task->data );
		} catch ( ExitException $e ) {
			// WordPress called exit() directly (e.g. auth_redirect() after wp_redirect()).
			// Build a PSR redirect response from the captured wp_redirect filter data
			// or from the PSR Headers class (patched WordPress fork via wp_header action).
			error_log( 'ExitException in task worker: ' . $e->getMessage() );

			// Prefer PSR-captured headers (patched WordPress fork via wp_header action).
			$headers_instance = Headers::getCurrent();
			$psr_headers      = $headers_instance ? $headers_instance->get_headers() : array();
			$psr_status       = $headers_instance ? $headers_instance->get_status_code() : 200;
			if ( $headers_instance ) {
				$headers_instance->reset();
			}

			// Merge redirect info: per-request filter takes priority, then mu-plugin global.
			$captured_location = $redirect_info['location'] ?? ( $GLOBALS['_swoole_redirect']['location'] ?? null );
			$captured_status   = $redirect_info['location'] ? $redirect_info['status'] : ( $GLOBALS['_swoole_redirect']['status'] ?? 302 );
			unset( $GLOBALS['_swoole_redirect'] );

			if ( ! empty( $psr_headers ) || $psr_status !== 200 ) {
				// Patched WordPress fork: headers captured via wp_header action.
				$response = $psr17->createResponse( $psr_status > 0 ? $psr_status : 302 );
				foreach ( $psr_headers as $header => $value ) {
					$response = $response->withHeader( $header, $value );
				}
			} elseif ( null !== $captured_location ) {
				// Standard WordPress: redirect captured via wp_redirect filter.
				$response = $psr17->createResponse( $captured_status );
				$response = $response->withHeader( 'Location', $captured_location );
				error_log( 'ExitException redirect: status=' . $captured_status . ' location=' . $captured_location );
			} else {
				// Fallback: unknown exit, return 500.
				error_log( 'ExitException in task worker with no redirect info captured.' );
				$response = $psr17->createResponse( 500 );
			}
		} finally {
			// Always remove the per-request filter to avoid accumulation across requests.
			if ( function_exists( 'remove_filter' ) ) {
				remove_filter( 'wp_redirect', $redirect_filter, PHP_INT_MAX );
			}
		}

		$task->finish( $response );
		if ( $task_workers->shouldShutdownAfter( $task->data ) ) {
			$server->stop();
		}
	}
);

$http->on(
	'WorkerStop',
	function ( $server, $worker_id ) {
		error_log( "Worker #$worker_id stopped" );
	}
);

if ( extension_loaded( 'inotify' ) && class_exists( \Mezzio\Swoole\HotCodeReload\FileWatcher\InotifyFileWatcher::class ) ) {
	$inotify = new \Mezzio\Swoole\HotCodeReload\FileWatcher\InotifyFileWatcher();
	$inotify->addFilePath( $wordpres_path );

	$http->tick(
		555,
		function () use ( $inotify, $http ) {

			$changed_file_paths = $inotify->readChangedFilePaths();

			if ( ! $changed_file_paths ) {
				return;
			}
			foreach ( $changed_file_paths as $path ) {
				echo "Reloading due to file change: $path";
			}
			$http->reload();
		}
	);
}
$http->start();
